### ISSUE TITLE
Not work, even no any useful logs

### ISSUE THREAD

**Issue by GreatFireWall** [databacker/mysql-backup#114]
![image](https://user-images.githubusercontent.com/4510984/60753254-11c4ce00-a002-11e9-95ac-0d67930ca6a8.png)

![image](https://user-images.githubusercontent.com/4510984/60753347-50a75380-a003-11e9-9283-79cb459abf64.png)

![image](https://user-images.githubusercontent.com/4510984/60753300-bb0bc400-a002-11e9-9ea2-df05729d3ee2.png)

![image](https://user-images.githubusercontent.com/4510984/60753306-d7a7fc00-a002-11e9-9b4b-bcdb619d9a26.png)

![image](https://user-images.githubusercontent.com/4510984/60753314-f27a7080-a002-11e9-873c-09314a1b6b2b.png)

![image](https://user-images.githubusercontent.com/4510984/60753338-34a3b200-a003-11e9-9582-5c2c4c5eda3d.png)

**Comment by deitch** [comment]
Run it in debug mode, see what you get for logs.

**Comment by GreatFireWall** [comment]
The same, no logs except the previous post image.

**Comment by deitch** [comment]
That isn't right. The very beginning of the entrypoint is:

```sh
if [[ -n "$DB_DUMP_DEBUG" ]]; then
  set -x
fi
```

So you should get lots of output. Are you setting `DB_DUMP_DEBUG` to `true` (or some other valid string)?

**Comment by GreatFireWall** [comment]
> That isn't right. The very beginning of the entrypoint is:
> 
> ```shell
> if [[ -n "$DB_DUMP_DEBUG" ]]; then
>   set -x
> fi
> ```
> 
> So you should get lots of output. Are you setting `DB_DUMP_DEBUG` to `true` (or some other valid string)?

Sorry my mistake, now I can see it's `Permission denied`.

**Comment by GreatFireWall** [comment]
![image](https://user-images.githubusercontent.com/4510984/60765804-9121d280-a0d2-11e9-991f-04ef1ba7da76.png)

How can I solve this without run as root ?

**Comment by deitch** [comment]
Ah. That would come out even without debug enabled (but it didn't hurt, other than needing to sift through logs).

It is a classic container bind-mount permissions issue. You could make the mounted directory `0777` if you want, or use a docker volume rather than a local dir, or run backup as a different user. It doesn't need to be root unless the current directory is restricted to writing to root.

**Comment by GreatFireWall** [comment]
Why my `mysql` no the issue.. They seems same ways to mount.

**Comment by deitch** [comment]
`mysql` image starts as root, then `mysqld` itself runs as a different user `mysql`. In its initialization script it does a `chown`, see [here](https://github.com/docker-library/mysql/blob/3362baccb4352bcf0022014f67c1ec7e6808b8c5/8.0/docker-entrypoint.sh#L90)

**Comment by GreatFireWall** [comment]
Understood, thank you !
