### ISSUE TITLE
Backup wont work if database is using     command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW

### ISSUE THREAD

**Issue by Akruidenberg** [databacker/mysql-backup#116]
I have a nextcloud server running with a mysql databse. It works very well with this container.
Last week i"ve reinstalled nextcloud but with the recommand setting     command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW

Now i got this error:

Log:

mysqldump: Got error: 1044: "Access denied for user 'nextcloud'@'%' to database 'nextcloud-mariadb'" when selecting the database,
rm: can't remove '/tmp/backups/db_backup_20190804135310.tgz': No such file or directory,Starting at Sun Aug 4 15:53:10 CEST 2019,
cp: can't stat '/tmp/backups/db_backup_20190804135310.tgz': No such file or directory

How to fix this?

Thanks!

**Comment by deitch** [comment]
Can you run it in debug mode? Set the env var `DB_DUMP_DEBUG=true` (or if in a docker container `-e DB_DUMP_DEBUG=true`, in Kubernetes the correct `yml` etc), and then paste the relevant part of the output here. Be careful not to paste here any sensitive data.

**Comment by Akruidenberg** [comment]
Here we go!

mysql-backup         | + file_env DB_SERVER
mysql-backup         | + local var=DB_SERVER
mysql-backup         | + local fileVar=DB_SERVER_FILE
mysql-backup         | + local def=
mysql-backup         | + '[' nextcloud-mariadb ']'
mysql-backup         | + '[' '' ']'
mysql-backup         | + local val=
mysql-backup         | + '[' nextcloud-mariadb ']'
mysql-backup         | + val=nextcloud-mariadb
mysql-backup         | + export DB_SERVER=nextcloud-mariadb
mysql-backup         | + DB_SERVER=nextcloud-mariadb
mysql-backup         | + unset DB_SERVER_FILE
mysql-backup         | + file_env DB_PORT
mysql-backup         | + local var=DB_PORT
mysql-backup         | + local fileVar=DB_PORT_FILE
mysql-backup         | + local def=
mysql-backup         | + '[' 3306 ']'
mysql-backup         | + '[' '' ']'
mysql-backup         | + local val=
mysql-backup         | + '[' 3306 ']'
mysql-backup         | + val=3306
mysql-backup         | + export DB_PORT=3306
mysql-backup         | + DB_PORT=3306
mysql-backup         | + unset DB_PORT_FILE
mysql-backup         | + file_env DB_USER
mysql-backup         | + local var=DB_USER
mysql-backup         | + local fileVar=DB_USER_FILE
mysql-backup         | + local def=
mysql-backup         | + '[' nextcloud ']'
mysql-backup         | + '[' '' ']'
mysql-backup         | + local val=
mysql-backup         | + '[' nextcloud ']'
mysql-backup         | + val=nextcloud
mysql-backup         | + export DB_USER=nextcloud
mysql-backup         | + DB_USER=nextcloud
mysql-backup         | + unset DB_USER_FILE
mysql-backup         | + file_env DB_PASS
mysql-backup         | + local var=DB_PASS
mysql-backup         | + local fileVar=DB_PASS_FILE
mysql-backup         | + local def=
mysql-backup         | + '[' '***********' ']'
mysql-backup         | + '[' '' ']'
mysql-backup         | + local val=
mysql-backup         | + '[' '***************' ']'
mysql-backup         | + val='**************'
mysql-backup         | + export 'DB_PASS=****************'
mysql-backup         | + DB_PASS='***************'
mysql-backup         | + unset DB_PASS_FILE
mysql-backup         | + file_env DB_NAMES
mysql-backup         | + local var=DB_NAMES
mysql-backup         | + local fileVar=DB_NAMES_FILE
mysql-backup         | + local def=
mysql-backup         | + '[' nextcloud-mariadb ']'
mysql-backup         | + '[' '' ']'
mysql-backup         | + local val=
mysql-backup         | + '[' nextcloud-mariadb ']'
mysql-backup         | + val=nextcloud-mariadb
mysql-backup         | + export DB_NAMES=nextcloud-mariadb
mysql-backup         | + DB_NAMES=nextcloud-mariadb
mysql-backup         | + unset DB_NAMES_FILE
mysql-backup         | + file_env DB_DUMP_FREQ 1440
mysql-backup         | + local var=DB_DUMP_FREQ
mysql-backup         | + local fileVar=DB_DUMP_FREQ_FILE
mysql-backup         | + local def=1440
mysql-backup         | + '[' '' ']'
mysql-backup         | + local val=1440
mysql-backup         | + '[' '' ']'
mysql-backup         | + '[' '' ']'
mysql-backup         | + export DB_DUMP_FREQ=1440
mysql-backup         | + DB_DUMP_FREQ=1440
mysql-backup         | + unset DB_DUMP_FREQ_FILE
mysql-backup         | + file_env DB_DUMP_BEGIN +0
mysql-backup         | + local var=DB_DUMP_BEGIN
mysql-backup         | + local fileVar=DB_DUMP_BEGIN_FILE
mysql-backup         | + local def=+0
mysql-backup         | + '[' '' ']'
mysql-backup         | + local val=+0
mysql-backup         | + '[' '' ']'
mysql-backup         | + '[' '' ']'
mysql-backup         | + export DB_DUMP_BEGIN=+0
mysql-backup         | + DB_DUMP_BEGIN=+0
mysql-backup         | + unset DB_DUMP_BEGIN_FILE
mysql-backup         | + file_env DB_DUMP_DEBUG
mysql-backup         | + local var=DB_DUMP_DEBUG
mysql-backup         | + local fileVar=DB_DUMP_DEBUG_FILE
mysql-backup         | + local def=
mysql-backup         | + '[' true ']'
mysql-backup         | + '[' '' ']'
mysql-backup         | + local val=
mysql-backup         | + '[' true ']'
mysql-backup         | + val=true
mysql-backup         | + export DB_DUMP_DEBUG=true
mysql-backup         | + DB_DUMP_DEBUG=true
mysql-backup         | + unset DB_DUMP_DEBUG_FILE
mysql-backup         | + file_env DB_DUMP_TARGET /backup
mysql-backup         | + local var=DB_DUMP_TARGET
mysql-backup         | + local fileVar=DB_DUMP_TARGET_FILE
mysql-backup         | + local def=/backup
mysql-backup         | + '[' /db/ ']'
mysql-backup         | + '[' '' ']'
mysql-backup         | + local val=/backup
mysql-backup         | + '[' /db/ ']'
mysql-backup         | + val=/db/
mysql-backup         | + export DB_DUMP_TARGET=/db/
mysql-backup         | + DB_DUMP_TARGET=/db/
mysql-backup         | + unset DB_DUMP_TARGET_FILE
mysql-backup         | + file_env DB_DUMP_BY_SCHEMA
mysql-backup         | + local var=DB_DUMP_BY_SCHEMA
mysql-backup         | + local fileVar=DB_DUMP_BY_SCHEMA_FILE
mysql-backup         | + local def=
mysql-backup         | + '[' '' ']'
mysql-backup         | + local val=
mysql-backup         | + '[' '' ']'
mysql-backup         | + '[' '' ']'
mysql-backup         | + export DB_DUMP_BY_SCHEMA=
mysql-backup         | + DB_DUMP_BY_SCHEMA=
mysql-backup         | + unset DB_DUMP_BY_SCHEMA_FILE
mysql-backup         | + file_env DB_DUMP_KEEP_PERMISSIONS true
mysql-backup         | + local var=DB_DUMP_KEEP_PERMISSIONS
mysql-backup         | + local fileVar=DB_DUMP_KEEP_PERMISSIONS_FILE
mysql-backup         | + local def=true
mysql-backup         | + '[' '' ']'
mysql-backup         | + local val=true
mysql-backup         | + '[' '' ']'
mysql-backup         | + '[' '' ']'
mysql-backup         | + export DB_DUMP_KEEP_PERMISSIONS=true
mysql-backup         | + DB_DUMP_KEEP_PERMISSIONS=true
mysql-backup         | + unset DB_DUMP_KEEP_PERMISSIONS_FILE
mysql-backup         | + file_env DB_RESTORE_TARGET
mysql-backup         | + local var=DB_RESTORE_TARGET
mysql-backup         | + local fileVar=DB_RESTORE_TARGET_FILE
mysql-backup         | + local def=
mysql-backup         | + '[' '' ']'
mysql-backup         | + local val=
mysql-backup         | + '[' '' ']'
mysql-backup         | + '[' '' ']'
mysql-backup         | + export DB_RESTORE_TARGET=
mysql-backup         | + DB_RESTORE_TARGET=
mysql-backup         | + unset DB_RESTORE_TARGET_FILE
mysql-backup         | + file_env AWS_ENDPOINT_URL
mysql-backup         | + local var=AWS_ENDPOINT_URL
mysql-backup         | + local fileVar=AWS_ENDPOINT_URL_FILE
mysql-backup         | + local def=
mysql-backup         | + '[' '' ']'
mysql-backup         | + local val=
mysql-backup         | + '[' '' ']'
mysql-backup         | + '[' '' ']'
mysql-backup         | + export AWS_ENDPOINT_URL=
mysql-backup         | + AWS_ENDPOINT_URL=
mysql-backup         | + unset AWS_ENDPOINT_URL_FILE
mysql-backup         | + file_env AWS_ENDPOINT_OPT
mysql-backup         | + local var=AWS_ENDPOINT_OPT
mysql-backup         | + local fileVar=AWS_ENDPOINT_OPT_FILE
mysql-backup         | + local def=
mysql-backup         | + '[' '' ']'
mysql-backup         | + local val=
mysql-backup         | + '[' '' ']'
mysql-backup         | + '[' '' ']'
mysql-backup         | + export AWS_ENDPOINT_OPT=
mysql-backup         | + AWS_ENDPOINT_OPT=
mysql-backup         | + unset AWS_ENDPOINT_OPT_FILE
mysql-backup         | + file_env AWS_ACCESS_KEY_ID
mysql-backup         | + local var=AWS_ACCESS_KEY_ID
mysql-backup         | + local fileVar=AWS_ACCESS_KEY_ID_FILE
mysql-backup         | + local def=
mysql-backup         | + '[' '' ']'
mysql-backup         | + local val=
mysql-backup         | + '[' '' ']'
mysql-backup         | + '[' '' ']'
mysql-backup         | + export AWS_ACCESS_KEY_ID=
mysql-backup         | + AWS_ACCESS_KEY_ID=
mysql-backup         | + unset AWS_ACCESS_KEY_ID_FILE
mysql-backup         | + file_env AWS_SECRET_ACCESS_KEY
mysql-backup         | + local var=AWS_SECRET_ACCESS_KEY
mysql-backup         | + local fileVar=AWS_SECRET_ACCESS_KEY_FILE
mysql-backup         | + local def=
mysql-backup         | + '[' '' ']'
mysql-backup         | + local val=
mysql-backup         | + '[' '' ']'
mysql-backup         | + '[' '' ']'
mysql-backup         | + export AWS_SECRET_ACCESS_KEY=
mysql-backup         | + AWS_SECRET_ACCESS_KEY=
mysql-backup         | + unset AWS_SECRET_ACCESS_KEY_FILE
mysql-backup         | + file_env AWS_DEFAULT_REGION
mysql-backup         | + local var=AWS_DEFAULT_REGION
mysql-backup         | + local fileVar=AWS_DEFAULT_REGION_FILE
mysql-backup         | + local def=
mysql-backup         | + '[' '' ']'
mysql-backup         | + local val=
mysql-backup         | + '[' '' ']'
mysql-backup         | + '[' '' ']'
mysql-backup         | + export AWS_DEFAULT_REGION=
mysql-backup         | + AWS_DEFAULT_REGION=
mysql-backup         | + unset AWS_DEFAULT_REGION_FILE
mysql-backup         | + file_env SMB_USER
mysql-backup         | + local var=SMB_USER
mysql-backup         | + local fileVar=SMB_USER_FILE
mysql-backup         | + local def=
mysql-backup         | + '[' '' ']'
mysql-backup         | + local val=
mysql-backup         | + '[' '' ']'
mysql-backup         | + '[' '' ']'
mysql-backup         | + export SMB_USER=
mysql-backup         | + SMB_USER=
mysql-backup         | + unset SMB_USER_FILE
mysql-backup         | + file_env SMB_PASS
mysql-backup         | + local var=SMB_PASS
mysql-backup         | + local fileVar=SMB_PASS_FILE
mysql-backup         | + local def=
mysql-backup         | + '[' '' ']'
mysql-backup         | + local val=
mysql-backup         | + '[' '' ']'
mysql-backup         | + '[' '' ']'
mysql-backup         | + export SMB_PASS=
mysql-backup         | + SMB_PASS=
mysql-backup         | + unset SMB_PASS_FILE
mysql-backup         | + file_env COMPRESSION gzip
mysql-backup         | + local var=COMPRESSION
mysql-backup         | + local fileVar=COMPRESSION_FILE
mysql-backup         | + local def=gzip
mysql-backup         | + '[' '' ']'
mysql-backup         | + local val=gzip
mysql-backup         | + '[' '' ']'
mysql-backup         | + '[' '' ']'
mysql-backup         | + export COMPRESSION=gzip
mysql-backup         | + COMPRESSION=gzip
mysql-backup         | + unset COMPRESSION_FILE
mysql-backup         | + [[ -n true ]]
mysql-backup         | + set -x
mysql-backup         | + MYSQLDUMP_OPTS=
mysql-backup         | + '[' -n nextcloud ']'
mysql-backup         | + DBUSER=-unextcloud
mysql-backup         | + '[' -n '*************************' ']'
mysql-backup         | + DBPASS='-***********************'
mysql-backup         | + '[' -z nextcloud-mariadb ']'
mysql-backup         | + '[' -z 3306 ']'
mysql-backup         | + COMPRESS=
mysql-backup         | + UNCOMPRESS=
mysql-backup         | + case $COMPRESSION in
mysql-backup         | + COMPRESS=gzip
mysql-backup         | + UNCOMPRESS=gunzip
mysql-backup         | + EXTENSION=tgz
mysql-backup         | + TMPDIR=/tmp/backups
mysql-backup         | + TMPRESTORE=/tmp/restorefile
mysql-backup         | + declare -A uri
mysql-backup         | + [[ -n '' ]]
mysql-backup         | ++ date
mysql-backup         | + echo Starting at Sun Aug 4 17:22:12 CEST 2019
mysql-backup         | Starting at Sun Aug 4 17:22:12 CEST 2019
mysql-backup         | + last_run=0
mysql-backup         | ++ date +%s
mysql-backup         | + current_time=1564932132
mysql-backup         | + freq_time=86400
mysql-backup         | + '[' -n '' ']'
mysql-backup         | + [[ +0 =~ ^\+(.*)$ ]]
mysql-backup         | + waittime=0
mysql-backup         | + target_time=1564932132
mysql-backup         | + '[' -z '' ']'
mysql-backup         | + sleep 0
mysql-backup         | ++ date +%s
mysql-backup         | + last_run=1564932132
mysql-backup         | + exit_code=0
mysql-backup         | + true
mysql-backup         | + mkdir -p /tmp/backups
mysql-backup         | + do_dump
mysql-backup         | ++ date -u +%Y%m%d%H%M%S
mysql-backup         | + now=20190804152212
mysql-backup         | + SOURCE=db_backup_20190804152212.tgz
mysql-backup         | + TARGET=db_backup_20190804152212.tgz
mysql-backup         | + '[' -d /scripts.d/pre-backup/ ']'
mysql-backup         | + workdir=/tmp/backup.1
mysql-backup         | + rm -rf /tmp/backup.1
mysql-backup         | + mkdir -p /tmp/backup.1
mysql-backup         | + '[' -n '' -a '' = true ']'
mysql-backup         | + [[ -n nextcloud-mariadb ]]
mysql-backup         | + DB_LIST='--databases nextcloud-mariadb'
mysql-backup         | + mysqldump -h nextcloud-mariadb -P 3306 -unextcloud '-**********************' --databases nextcloud-mariadb
mysql-backup         | mysqldump: Got error: 1044: "Access denied for user 'nextcloud'@'%' to database 'nextcloud-mariadb'" when selecting the database
mysql-backup         | + '[' 2 -ne 0 ']'
mysql-backup         | + return 1
mysql-backup         | + '[' 1 -ne 0 ']'
mysql-backup         | + exit_code=1
mysql-backup         | + for target in ${DB_DUMP_TARGET}
mysql-backup         | + backup_target /db/
mysql-backup         | + local target=/db/
mysql-backup         | + uri_parser /db/
mysql-backup         | + uri=()
mysql-backup         | + full=/db/
mysql-backup         | + full=/db/
mysql-backup         | + full=/db/
mysql-backup         | + [[ / == \/ ]]
mysql-backup         | + full=file://localhost/db/
mysql-backup         | + [[ file://l == \f\i\l\e\:\/\/\/ ]]
mysql-backup         | + pattern='^(([a-z0-9]{2,5})://)?((([^:\/]+)(:([^@\/]*))?@)?([^:\/?]+)(:([0-9]+))?)(\/[^?]*)?(\?[^#]*)?(#.*)?$'
mysql-backup         | + [[ file://localhost/db/ =~ ^(([a-z0-9]{2,5})://)?((([^:\/]+)(:([^@\/]*))?@)?([^:\/?]+)(:([0-9]+))?)(\/[^?]*)?(\?[^#]*)?(#.*)?$ ]]
mysql-backup         | + full=file://localhost/db/
mysql-backup         | + uri[uri]=file://localhost/db/
mysql-backup         | + uri[schema]=file
mysql-backup         | + uri[address]=localhost
mysql-backup         | + uri[user]=
mysql-backup         | + uri[password]=
mysql-backup         | + uri[host]=localhost
mysql-backup         | + uri[port]=
mysql-backup         | + uri[path]=/db/
mysql-backup         | + uri[query]=
mysql-backup         | + uri[fragment]=
mysql-backup         | + [[ file == \s\m\b ]]
mysql-backup         | + [[ -n '' ]]
mysql-backup         | + return 0
mysql-backup         | + case "${uri[schema]}" in
mysql-backup         | + mkdir -p /db/
mysql-backup         | + cpOpts=-a
mysql-backup         | + '[' -n true -a true = false ']'
mysql-backup         | + cp -a /tmp/backups/db_backup_20190804152212.tgz /db//db_backup_20190804152212.tgz
mysql-backup         | cp: can't stat '/tmp/backups/db_backup_20190804152212.tgz': No such file or directory
mysql-backup         | + '[' 1 -ne 0 ']'
mysql-backup         | + return 1
mysql-backup         | + '[' 1 -ne 0 ']'
mysql-backup         | + exit_code=1
mysql-backup         | + /bin/rm /tmp/backups/db_backup_20190804152212.tgz
mysql-backup         | rm: can't remove '/tmp/backups/db_backup_20190804152212.tgz': No such file or directory
mysql-backup         | ++ date +%s
mysql-backup         | + current_time=1564932132
mysql-backup         | + '[' -n '' ']'
mysql-backup         | + '[' -n '' ']'
mysql-backup         | ++ date +%s
mysql-backup         | + current_time=1564932132
mysql-backup         | + backup_time=0
mysql-backup         | + freq_time_count=0
mysql-backup         | + freq_time_count_to_add=1
mysql-backup         | + extra_time=86400
mysql-backup         | + target_time=1565018532
mysql-backup         | + waittime=86400
mysql-backup         | + sleep 86400

**Comment by Akruidenberg** [comment]
problem resolved. Wrong database name was provided. Now it works very well. Closed.

**Comment by deitch** [comment]
> Wrong database name was provided

Don't you hate when that happens. I do that far too frequently, just finish with [PEBKAC](https://en.wiktionary.org/wiki/PEBCAK), have a good laugh at myself (and sometimes, depending on how much time I spent, a stiff drink, too).
