### ISSUE TITLE
Managing ownership of backups

### ISSUE THREAD

**Issue by Glideh** [databacker/mysql-backup#120]
Thank you for this great image, it's very useful and well thought out.
I'm integrating it in one of my docker composition and I'm trying to do so I can easily deploy it anywhere else.
In the doc, when we need to put backups in a host mounted volume, you suggest to specify the UID in `docker-compose.yml`
Since I'll use it in other hosts, I would always need to adjust this UID to match the id of the user which runs the containers.
How can I avoid that ?
Is there a way to make it dump the backups keeping the same user that runs it, without having to ajust the UID for each new host ?

**Comment by deitch** [comment]
I am not sure I understand the question. Let me give it a shot, though.

This is the classic problem of one process writing to a dir that needs to be read/written by another. It isn't the UID that "runs the containers" that matters, as much as the UID of the process _inside_ the container that matters. 

What would be wrong with running it as, say, UID 1005 (or 2010 or 6667 or anything else) on all of the hosts, and ensuring the directory is writable to that UID on all of them?

**Comment by Glideh** [comment]
There would be nothing wrong about it.
My concern is just an optimisation one, in terms of simplicity out of the box.
I was trying to find a way to be able to run the image without having to take care about permissions.
Maybe I could somehow pass the ${UID} of the current user in the env variable or something like that.

**Comment by deitch** [comment]
Oh, that would be interesting. Truth is, though, that docker providers the ability to specify it, or in the compose file, as you wrote above.

Forget for a moment the implementation mechanism. What would the flow you are recommending look like? How would you use it? I am trying to grasp what an ideal flow would be.

**Comment by Glideh** [comment]
If you are talking about the ideal usage of the image, I'd say it's already close from ideal.
What I usually like in such images is the default behavior, I mean the image can be run with the less required environment variables (which is already the case).
If we are able to apply the current user's ID (still having the ability to override it) to the backup files by default, it would be great and it would not break backward compatibility.

**Comment by deitch** [comment]
> apply the current user's ID

When you say "current user's ID", what do you mean? Assuming the container is run via some system like swarm or kubernetes, or even just compose, it is a daemon that is running it. What "user" is the "current user"?

**Comment by Glideh** [comment]
It can always be run manually, but when it's a daemon I guess it should take the user configured in the daemon.

**Comment by deitch** [comment]
> I guess it should take the user configured in the daemon.

I don't think so. That kind of goes against the grain of containers. The daemon - dockerd, kubelet, or actual runtime like containerd - is running a lot of containers, most of which (should) have limited privileges and different IDs.

**Comment by Glideh** [comment]
Yes I understand that and I agree. Shouldn't we have this ownership decision order:

- User configured for the service (which would be what you refer to as "limited privileges and different IDs")
- Specific orchestration tool user management selection
- Daemon user
- ... root

**Comment by deitch** [comment]
Well, the first is what it is now. The second is overridable as-is by anything that can orchestrate (compose has a user option, so does kubernetes, etc.), so those work already. 

Daemon user isn't even discoverable by the container; it just doesn't know.

**Comment by Glideh** [comment]
I imagine a "daemon user" is supposed to be used to run the process (the process doesn't need to guess it).
For example if I configure nginx to run as `www-data`, it'll read/write the files with this user.
It'll do the same as if I'm running the thing manually with the given user.

**Comment by deitch** [comment]
It isn't. The container runtime decides what process to use to run the container's process, based on the runtime config, which is set by whatever instantiates it. The OCI spec determines [here](https://github.com/opencontainers/runtime-spec/blob/master/config.md#user) what the user process should be. 

As far as I know, every runtime instantiator defaults to root, unless overridden with a specific option, e.g. `docker run --user <user>` or kubernetes' `runAsUser`, etc., which pass it all on to the runtime.

**Comment by Glideh** [comment]
Thank you for this information.
I'm closing this for now.
If someone have an idea don't hesitate to tell it here.
