### ISSUE TITLE
Properly tag docker images

### ISSUE THREAD

**Issue by matejhasul** [databacker/mysql-backup#129]
Hi,
do you plan to tag docker images in https://hub.docker.com/r/databack/mysql-backup with release tag? There is only `latest` tag and I'm afraid to use rolling `latest` tag in prod.

**Comment by deitch** [comment]
Very good point. We should get the tags in on this. We have been using git tree hashes as tags, to guarantee immutability. I _definitely_ wouldn't use `latest` - I avoid it in everything prod I do, and most non-prod too - but I always am comfortable with fixed hash-based tags (or sha hashes of the image, of course).

Let's leave this open, try and get in the tags early next week

**Comment by matejhasul** [comment]
Thanks for quick response.

**Comment by deitch** [comment]
And finally done. I randomly (ok, not _so_ randomly) picked 0.10.0 for the current iteration. Will cut a 1.0.0 soon enough.

**Comment by matejhasul** [comment]
Thanks!
