### ISSUE TITLE
Add exclude database option

### ISSUE THREAD

**Issue by alexanderhofstaetter** [databacker/mysql-backup#138]
Hello!

Next to the `DB_NAMES ` option it would be nice to have an exclude option for single databases. E.g. I would like to backup all databases except one.

The problem I am facing is that when I export all of my databases with the backup user i created (SELECT and LOCK TABLE permissions) the script also tries to dump `information_schema` which leads to some permission errors.

```
mysqldump -h mariadb -P 3306 -ubackup -pXX --databases information_schema --single-transaction
mysql-backup    | mysqldump: Couldn't execute 'SELECT /*!40001 SQL_NO_CACHE */ `SPACE`, `PATH` FROM `INNODB_SYS_DATAFILES`': Access denied; you need (at least one of) the PROCESS privilege(s) for this operation (1227)
```

Maybe theese databases should be excluded by default? My use case ist that i want a separate backup file for each of my databases.

**Comment by alexanderhofstaetter** [comment]
**Update**: I took a look into the code and added the `DB_NAMES_EXCLUDE` environment variable. See pull request #139

**Comment by stefanheinrichsen** [comment]
I guess this can be set to resolved/closed now.

**Comment by deitch** [comment]
Sure can!
