### ISSUE TITLE
Proper usage for DB_NAMES

### ISSUE THREAD

**Issue by bwoodworth** [databacker/mysql-backup#144]
I am having trouble figuring out how to select multiple databases to be backed up.  Can someone provide and example value for that variable for selecting more than one database?

**Comment by deitch** [comment]
Yeah, this probably should be better documented. It is just setting `DB_NAMES` to be a space-separated list of databases. As simple as:

```
DB_NAMES="db1 db2 mydb"
```

Or if you prefer:

```
docker run -e DB_NAMES="db1 db2 mydb" ...
```

**Comment by bwoodworth** [comment]
Thanks!
