### ISSUE TITLE
Feature request: use custom tmp directory

### ISSUE THREAD

**Issue by danparisi** [databacker/mysql-backup#168]
It would be good if you add the chance to change the _tmp_ directory path. 
In my case, the application runs over a k8s POD and it's often evicted because consuming too much ephemeral storage, probably because the backup is created in such directory before being moved to _DB_DUMP_TARGET_.

For example, you could add an additional environment variable **DB_DUMP_TMP** or **WORKDIR** or both, as I see from the code you need more directories to make the thing works.

**Comment by deitch** [comment]
Great idea. Care to open a PR?

**Comment by danparisi** [comment]
Here is the PR: #169

**Comment by danparisi** [comment]
Thanks @deitch!

Just a reminder: the latest image (and documentation) is not updated in docker hub

**Comment by deitch** [comment]
The hub image for `master` and the specific commit `f16b96517ccd09f1184e620c8292a5d4f3555a43` are up to date. You are right that `latest` is not and the README on the main hub page is not. Will need to check into that.

**Comment by deitch** [comment]
OK, `latest` now points to the most recent semver release, and `master` points to the hash-tagged head of the master branch. That part is fixed. As for the `README` absorbed into the docker hub page, it needs to be done manually, unfortunately. I will update it once.
