### ISSUE TITLE
Latest upgrade breaks service & maxes CPU

### ISSUE THREAD

**Issue by waynehaffenden** [databacker/mysql-backup#171]
Our containers were automatically upgraded to the latest version of this image this morning and maxed out our server CPU (we run multiple of these - one for each client site). When viewing the log, they all show:

y2xsk  ./backup_2021-11-30T14:52:12Z.sql
y2xsk  date: invalid date ‘2021-11-31T0:0:00’
y2xsk  sleep: invalid option -- '1'
y2xsk  Try 'sleep --help' for more information.
y2xsk  ./

Please advise, we've had to stop all services running which means our client sites now have no database backups!

**Comment by deitch** [comment]
Interesting bug. Can you paste your launch command or compose file here (minus secrets of course)?

In the meantime, you never should use the `latest` tag on anything production. Pick a specific semver release or fixed hash tag.

**Comment by waynehaffenden** [comment]
Thanks @deitch it's running under docker swarm, the compose/stack file "part" is:

`
  backup:
    image: databack/mysql-backup
    networks:
      - internal
    volumes:
      - /swarm/scripts/backup/post:/scripts.d/post-backup:ro
      - /swarm/clients/abc123/website/data/backup:/backup
    environment:
      - COMPRESSION=bzip2
      - DB_DUMP_CRON=0 0 * * *
      - DB_DUMP_TARGET=/backup
      - DB_PASS_FILE=/run/secrets/abc123_website_database-password
      - DB_SERVER=localhost
      - DB_USER=abc123_website
    secrets:
      - abc123_database-password
    deploy:
      update_config:
        failure_action: rollback
      resources:
        limits:
          memory: 16M
        reservations:
          memory: 8M
      labels:
        swarmpit.service.deployment.autoredeploy: "true"
`

This worked before, good shout, I'll use the previous tag to get things running again for now until you find a fix. Appears to be two issues, once with it trying to generate 31st of November which of course is invalid and then an invalid argument to the sleep command.

**Comment by deitch** [comment]
Can you run it with `DB_DUMP_DEBUG=true` and paste the output here (minus any sensitive data, of course)?

Scripts are wonderful, but you hit the limits of their capabilities at times.

**Comment by flipkick** [comment]
The bug is located in the date calculation. The script calculates the 31th of November as the subsequent day of the 30th of November. This is an invalid date. The correct day would be the 1st of December.

**Comment by deitch** [comment]
Ok but where? 

Please paste the output, so we can get  at it.

**Comment by waynehaffenden** [comment]
No bug now as the date is 1st, this is now working but imagine at the end of the month it'll break again!

**Comment by deitch** [comment]
We should replicate it. Suggest how?

**Comment by waynehaffenden** [comment]
@deitch if you have a test machine, change the date to 30th November and try it! I can't change the date on my live server and don't have a test environment

**Comment by flipkick** [comment]
We could use a testcase like #172. BTW, another cron test is currently failing for the current version.
