### ISSUE TITLE
Archive name format

### ISSUE THREAD

**Issue by max1c** [databacker/mysql-backup#191]
My backups are still using the "db_backup_2022-05-24T13-52-25Z.tgz" instead of the actual database name when using the DB_DUMP_BY_SCHEME=true and specifying the DB_NAMES=name. Is this expected behaviour? When extracted the file has the correct "name_2022-05-24T13-52-25Z.sql" format. I expect the archive to have the same format. Is there a way to make archives have the same format?

**Comment by deitch** [comment]
Yes, it is expected. The backup file always has that format. The `DB_DUMP_BY_SCHEMA` docs say:

```
DB_DUMP_BY_SCHEMA: Whether to use separate files per schema in the compressed file (true), or a single dump file (false). Defaults to false.
```

The important point is "separate files per scream in the compressed file". It still is a single tgz, but there now are multiple files, one per schema, in that tgz.

> When extracted the file has the correct "name_2022-05-24T13-52-25Z.sql" format. I expect the archive to have the same format. Is there a way to make archives have the same format?

How would that work? Let's say you have 3 schemas, so you have 3 files in the tgz: `A_2022-05-24T13-52-25Z.sql`, `B_2022-05-24T13-52-25Z.sql`, `C_2022-05-24T13-52-25Z.sql`. What would you call the single compressed tgz? `A` or `B` or `C` or `ABC` or `A_and_B_and_C`?

The tgz is a single file, so it has that consistent name.

**Comment by deitch** [comment]
> I'm also wondering if there's a way to structure the files by week/month etc. and limit how many .tgz are kept at all times. Is this something that's supported?

There has been discussion at various times about providing rotation, cleanup, archiving, etc. I am reluctant to put it in this process, as it eliminates its "do one job well". It also gets complex supporting multiple remote protocols.

To really do it right, we would need to (finally) break it out of its current shell paradigm. I have considered commercial support offerings for mysql-backup in order to provide support and thereby fund some of those efforts. But nothing decided yet.

**Comment by Glideh** [comment]
I personally use [another service](https://github.com/Glideh/docker-cron-rotate-backups) to rotate the files, like:

```yml
#...
  rotate:
    image: glide/cron-rotate-backups:0.1
    volumes:
      - ./backup:/data
    environment:
      ROTATE_CRON: "* * * * *"
      ROTATE_OPTIONS: "--daily=7 --weekly=4 --monthly=12 --yearly=2"
```

**Comment by max1c** [comment]
> I personally use [another service](https://github.com/Glideh/docker-cron-rotate-backups) to rotate the files, like:
> 
> ```yaml
> #...
>   rotate:
>     image: glide/cron-rotate-backups:0.1
>     volumes:
>       - ./backup:/data
>     environment:
>       ROTATE_CRON: "* * * * *"
>       ROTATE_OPTIONS: "--daily=7 --weekly=4 --monthly=12 --yearly=2"
> ```

This is great. I think this issue can be closed.
