### ISSUE TITLE
Configuration option for WEBHOOK_URL, available in scripts?

### ISSUE THREAD

**Issue by salvisbh** [databacker/mysql-backup#212]
It would be perfect if an ENV_Variable with a configurable WEBHOOK_URL was available in the shell scripts. This could for example be used to call webhooks like healthcheck.io with the backup result after the backup. If this is not desired, it would at least be helpful to install curl in the image.

A good example of a webhook usage can be found in the Postgres backup image of prodrigestivill, see https://github.com/prodrigestivill/docker-postgres-backup-local

**Comment by deitch** [comment]
That's a pretty good idea. Go for a PR?

**Comment by salvisbh** [comment]
Hi  Deitch, 

In the meantime, I used a different image for my backups because I work with multiple database types and I don't want to use a different image with different configurations for each database-type. I am implementing a 3-2-1 backup strategy with the following elements:

- DB backup: tiredofit/docker-db-backup (https://github.com/tiredofit/docker-db-backup)
- Volume backup: open/docker-volume-backup (https://github.com/offen/docker-volume-backup)
- Backup to other NAS and long term archive in S3 glacier deep archive: duplicati (https://docs.linuxserver.io/images/docker-duplicati)
- Monitoring of backup jobs: healthchecks.io (https://healthchecks.io/docs/)

So my issue becomes invalid and it can be closed. 
Many thanks

**Comment by deitch** [comment]
Glad it worked out.
