### ISSUE TITLE
Could not run on ARMv8 platform

### ISSUE THREAD

**Issue by duetg** [databacker/mysql-backup#215]
I tried to run the docker image on FriendlyARM NanoPi R5S, which has Rockchip RK3568B2 SoC within, got an error message:
'The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested'.
Is there any work around with this platform?

**Comment by duetg** [comment]
I use `docker buildx` to rebuild the image, now it is running. The command is  here.
`docker buildx build --platform=linux/arm64/v8 -t mysql-backup:1.0.0 .`
I will check the backup result later.

**Comment by deitch** [comment]
Yeah, this was originally built on x86_64. I myself run on an arm64 (Mac M1), and have migrated a lot of projects from single-arch to multi-arch. This is a good candidate for it.

**Comment by deitch** [comment]
Now pushing a multiarch image. @duetg could you run `databack/mysql-backup:d8bfa1872cd3bdc6cac83d227270e9286d50dd83` and see if it fits? I am looking at cutting a semver release on the next few days if all is clean.
