### ISSUE TITLE
"Failed to list database schemas" when performing backup

### ISSUE THREAD

**Issue by dabico** [databacker/mysql-backup#252]
Another issue was observed while working on #105. The MRE from before (https://github.com/dabico/mysql-backup-issue-105) was updated to allow easy replication. Here are the comments:

> I updated the image tag in the MRE. The previous issue has been resolved, but now I get an error saying:

```log
Error: error backing up: failed to list database schemas: could not get schemas: dial tcp :0: connect: connection refused
```

> I find this odd, especially since `DB_NAMES` is specified in my compose config. Am I missing something in the configuration?

_Originally posted by @dabico in https://github.com/databacker/mysql-backup/issues/105#issuecomment-1877306485_

> > Am I missing something in the configuration?

> Probably not. But once we get this all working, time to cut a new release candidate 😁

_Originally posted by @deitch in https://github.com/databacker/mysql-backup/issues/105#issuecomment-1877309925_

**Comment by deitch** [comment]
This issue has been fixed. Running some tests to see if it opened any new issues not caught by CI

**Comment by deitch** [comment]
Ready for a nice new look.
