### ISSUE TITLE
Go version: parsing of `begin` time fails

### ISSUE THREAD

**Issue by FluffyEscargot** [databacker/mysql-backup#267]
## Expected Behavior
Passing a 4 digit start time to the `begin` flag should work.

## Current Behavior
mysql-backup exits with an error

`ERRO[0000] error creating timer: invalid format for begin delay '0915': <nil> `

## Steps to Reproduce
on master branch:
`./mysql-backup dump --target /backup --begin 0915`

## Possible Solution
The regex for the begin flag in timer.go, checks for >3 matching groups, but there are only 3. Example 0915, matching groups 0915, 09, 15
Change the check to >2

## Possible Implementation
pkg/core/timer.go:83 change to:
```go
	case len(startTimeParts) > 2:
```

**Comment by FluffyEscargot** [comment]
After fixing, the start time parsing is also wrong when not in UTC timezone. The delay from current time to begin time is always computed in respect to UTC

Ran at 12:13 local time

before fix:
./mysql-backup dump --target /backup --begin 1220 -v 2
DEBU[0000] starting dump                                
DEBU[0000] Sleeping for 1h7m0s                          

after fix:
./mysql-backup dump --target /backup --begin 1220 -v 2
DEBU[0000] starting dump                                
DEBU[0000] Sleeping for 6m0s

**Comment by deitch** [comment]
> I agree, timezones are a pain

We could just join the flat earth society and pretend it is not a problem. 😄 




> The only inconsitency then, is that when running the binary outside docker or not in an alpine image, --cron and --begin don't behave the same

Is that true even if we always enforce Zulu time?

**Comment by deitch** [comment]
That makes a lot of sense.We should be consistent, whatever we do. I am going to do that, then we can try and figure out a way to add TZ consistently.

**Comment by deitch** [comment]
#271
