### ISSUE TITLE
Go version: Default port not being used

### ISSUE THREAD

**Issue by FluffyEscargot** [databacker/mysql-backup#269]
## Expected Behavior
Not passing the `--port` flag or env variable should make the program default to `3306`, as described in the configuration documentation.

## Current Behavior
The programm tries to use port 0.

`FATA[0000] error backing up: failed to list database schemas: could not get schemas: dial tcp 127.0.0.1:0: connect: connection refused`

## Steps to Reproduce
on master branch:
`./mysql-backup dump --target /backup --server 127.0.0.1`

## Possible Solution
Set the `connection.Port` value from the flag, even if it is the default value (i.e. flag is not set)

**Comment by anbg24** [comment]
I think this is a the same bug as in this issue - https://github.com/databacker/mysql-backup/issues/297 .

Theoretically the issue can be closed?

**Comment by deitch** [comment]
Yes, I will close it. Thank you @lightsuner . @FluffyEscargot if we are in error, reopen it, please.
