### ISSUE TITLE
Go version: Crashes on DATE, DATETIME and TIMESTAMP fields

### ISSUE THREAD

**Issue by FluffyEscargot** [databacker/mysql-backup#272]
## Expected Behavior
The program should dump all fields, also date/time fields.

## Current Behavior
Program crashes when trying to scan DATE, DATETIME or TIMESTAMP fields
`backup_test.go:590: failed to run dump test: error backing up: failed to dump database: failed to dump database tester: sql: Scan error on column index 2, name "test_time": unsupported Scan, storing driver.Value type []uint8 into type *time.Time`

## Steps to Reproduce
1. Run db with any of the mentioned field types: `create table t1 (id INT, name VARCHAR(20), test_time TIMESTAMP); INSERT INTO t1 (id,name,test_time) VALUES (1, "John", '2012-11-01 00:15:00');`
2. Try to dump the database: `mysql-backup dump --target /backup --server mysql`

## Possible Solution
1. Allow scanning of time fields using the mysql connection option `parseTime=true`
2. Add support for parsing time fields to properly print the to dump file
3. Potentially differentiate between DATETIME/TIMESTAMP and DATE for cleaner output

## Possible Implementation
pkg/database/connection.go:21
`config.ParseTime = true`

pkg/database/mysql/dump.go:562
```go
case *sql.NullTime:
	if s.Valid {
		fmt.Fprintf(&b, "'%s'", sanitize(s.Time.Format("2006-01-02 15:04:05")))
	} else {
		b.WriteString(nullType)
	}
```

**Comment by deitch** [comment]
based on #283 can this be closed?

**Comment by FluffyEscargot** [comment]
> based on #283 can this be closed?

Yeah looks great, clean solution!
