### ISSUE TITLE
Add support for configurable rolling backup retention period e.g Keep only latest 7 days of backups

### ISSUE THREAD

**Issue by pmharris77** [databacker/mysql-backup#274]

**Comment by deitch** [comment]
There have been requests for this before. I have been torn on it. On the one hand, I like the idea of this being clean: it runs a backup or it runs a restore, on a schedule. Adding a retention period makes it much more complex. It needs to check what is there before or after running, and maybe needs to check other things, and what if it doesn't have list or delete rights?

On the other hand, there is something to be said for taking advantage of the fact that it already is there, and running, to to some cleanup.

If you feel like putting together a simple design here, how the flow would work, what would enable/disable it and how it would be set, we can try and think it through.

**Comment by pmharris77** [comment]
I was thinking of something relatively simple as implemented for offen/docker-volume-backup [here](https://offen.github.io/docker-volume-backup/how-tos/automatically-prune-old-backups.html)?

Pruning code is [here](https://github.com/offen/docker-volume-backup/blob/main/cmd/backup/prune_backups.go)

There is a simple config ENV variable for the retention period in days (`BACKUP_RETENTION_DAYS`) and at the end of the backup, it checks to see if there are any backups older than the (current day - (BACKUP_RETENTION_DAYS+BACKUP_PRUNING_LEEWAY)) and prunes them. 

If the BACKUP_RETENTION_DAYS variable is not set, it does not do any pruning.

It also has some settings to exclude certain storage backends from the pruning process.

As you say, there would be more complications, such as list/delete rights for S3, but I imagine worst case any permissions errors in the S3 request could be caught and logged?

**Comment by deitch** [comment]
> If the BACKUP_RETENTION_DAYS variable is not set, it disables pruning

Of course. Makes sense. 

> There is a simple config ENV variable for the retention period in days (BACKUP_RETENTION_DAYS) and , it checks to see if there are any backups older than now() - (BACKUP_RETENTION_DAYS+BACKUP_PRUNING_LEEWAY) and prunes them.

> at the end of the backup

What happens if the backup fails? If we say, "keep 7 days", but today failed, then we have 7 days worth pre-prune, but one of them is 8 days old. Do we prioritize the _time_ (nothing >7 days) and delete it, or the _count_ (have 7 days worth of backups) and keep it?

> As you say, there would be more complications, such as list/delete rights for S3, but I imagine worst case any permissions errors in the S3 request could be caught and logged?

Yes, I think that is fair.

> BACKUP_PRUNING_LEEWAY

What is that?

What do we do about custom filenames? You can customize it, see [here](https://github.com/databacker/mysql-backup/blob/738a5d651d8501f6b17bcd4d1ed9df481eb8f557/docs/backup.md?plain=1#L247).

**Comment by pmharris77** [comment]
> What happens if the backup fails? If we say, "keep 7 days", but today failed, then we have 7 days worth pre-prune, but one of them is 8 days old. Do we prioritize the time (nothing >7 days) and delete it, or the count (have 7 days worth of backups) and keep it?

I would probably say that first check before pruning at the end of a backup should be if there are > BACKUP_RETENTION_DAYS worth of backup files.  If not, don't prune.  This would account for initial backups before we accumulate enough to hit the retention limit and for failing backups (e.g. backing storage full or write permissions suddenly failing)

> BACKUP_PRUNING_LEEWAY
What is that?

From the documentation, it is a tweak-factor that adds a delta on to the BACKUP_RETENTION_DAYS period to mitigate race conditions:

`In case the duration a backup takes fluctuates noticeably in your setup you can adjust this setting to make sure there are no race conditions between the backup finishing and the rotation not deleting backups that sit on the edge of the time window. Set this value to a duration that is expected to be bigger than the maximum difference of backups.
Valid values have a suffix of (s)econds, (m)inutes or (h)ours. By default,one minute is used.`

> What do we do about custom filenames?

Hmm, this is a bit trickier, but you would also have access to the same `--source-filename-pattern` setting that the user specifies, so could use that to find where the historic backups for prune checking should reside?  This is straightforward for single directory storage (e.g. `db-plus-wordpress_{{.now}}.gz`), but becomes harder if they have specified nested sub-directories based on the timestamp (e.g. `<root-dir>/<year>/<month>/<day>/mybackup_<timestamp>.gz`)

I suppose you could recursively search for all files that match the file prefix (minus any {{time}} substitution tokens) within <root-dir>, and instead use their metadata to find when they were created/modified (assuming all supported storage backends allow you to query/determine that)?

**Comment by deitch** [comment]
> tweak-factor that adds a delta on to the BACKUP_RETENTION_DAYS

Eh. I would avoid that for now. Keep it simple, and use a basic logic to allow some leeway. If you happen to miss deleting a backup for an extra day, that is OK. So if someone puts in "7 days", it is ok if the 8th day is there for a while.

> Hmm, this is a bit trickier, but you would also have access to the same --source-filename-pattern setting that the user specifies,

Or just avoid it for now. If you use a custom filename, retention is not supported as of yet. Someone could run it for 6 months with one pattern, and then switch, and there is no way to know what the old pattern was.

It also could be possible to just "delete any files in the tree older than X", but that can get really slow (especially on network connections), and is potentially dangerous. If you want that kind of cleanup, find a tool to do it.

Hmm... I kind of am warming to the idea.

**Comment by deitch** [comment]
@pmharris77 take a look at the docs in #277. I will let that sit for a few days, see that we have the UX correct, then we can move towards implementing.

**Comment by pmharris77** [comment]
> @pmharris77 take a look at the docs in #277. I will let that sit for a few days, see that we have the UX correct, then we can move towards implementing.

Have just had a read. All looks good. Thanks v much for adding this!
