### ISSUE TITLE
Cannot connect to mysql over the local unix domain socket

### ISSUE THREAD

**Issue by Ramblurr** [databacker/mysql-backup#285]
https://github.com/databacker/mysql-backup/blob/ea1580bf84037991162969b62c66c7d93ddc7a7f/pkg/database/connection.go#L20-L21

When running services locally with the mysql database we prefer to use unix domain sockets for connecting rather then TCP. The unix security model is easier to secure and grok when we don't need to go over the network.

Unfortunately as you can see in the referenced code `mysql-backup` hard codes the use of TCP.

If the `DB_SERVER` field starts with slash `/` then I think you can assume we are providing the path to the local unix domain socket, and then set `config.Net = "unix"`, assign it to `config.Addr` and then just ignore the port param.

**Comment by deitch** [comment]
I think that is a good idea. it is setting the driver based on [mysq.Config](https://pkg.go.dev/github.com/go-sql-driver/mysql#Config), which supports `hostname:port` or `/path/to/unix/domain/socket`, so the underlying system supports it.

The config currently uses `--server <IP/FQDN> --port <port>` (or env var or config file equivalents) to set those. How would you change it? Just replace `--server <IP/FQDN:port | /path/to/socket>`? Use the same parsing?

**Comment by Ramblurr** [comment]
Yes, I would re-use the `--server` flag as you described, and then ignore the port.. I having a working patch here:

https://github.com/Ramblurr/mysql-backup/commit/1e84d01eb41e3286419aad0f7a54d44518e0d671

**Comment by Ramblurr** [comment]
@deitch thanks for merging this! As soon as you can cut a new 1.0.0 rc release, then I'll be able to push along the distro packaging I'm working on.
