### ISSUE TITLE
golang mysql-backup does not implement the nice argument

### ISSUE THREAD

**Issue by Ramblurr** [databacker/mysql-backup#291]
The goland mysql-backup docs claim that it supports the nice parameter, but that feature is still missing from the codebase.

**Comment by Ramblurr** [comment]
Maybe we should mention the NICE option only applies when running in a container?

**Comment by deitch** [comment]
It does, see [configuration.md](https://github.com/databacker/mysql-backup/blob/master/docs/configuration.md), it says:

```
when in container, run the dump or restore with nice/ionice
```

**Comment by Ramblurr** [comment]
Doh! Can't read, sorry for the noise.

**Comment by deitch** [comment]
> Doh! Can't read, sorry for the noise.

😄
