### ISSUE TITLE
MariaDB Compatability issue

### ISSUE THREAD

**Issue by peerau** [databacker/mysql-backup#304]
https://github.com/databacker/mysql-backup/blob/master/pkg/database/mysql/dump.go#L92

MariaDB has no collat for utf8mb4\_0900\_\*, instead using uca1400\_\* (basically a newer version of the same collation)

**Comment by deitch** [comment]
The line there is:

```sql
CREATE DATABASE /*!32312 IF NOT EXISTS*/ ` + "`{{.Database}}`" + ` /*!40100 DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci */ /*!80016 DEFAULT ENCRYPTION='N' */;

USE ` + "`{{.Database}}`;"
```

Does this affect `utf8mb4_0900_ai_ci` for COLLATE only? Or `utf8mb4` for `DEFAULT CHARACTER SET` as well?

**Comment by deitch** [comment]
I assume you tested it. Did you end up with a successful dump, but then could not restore the file? And if that is the case, and you manually edited the file, did it then work? Which version(s) of MariaDB?

**Comment by peerau** [comment]
I changed the COLLATE to uca1400_, yes the default charset is fine - dumping and restoring from MariaDB 10.17

**Comment by deitch** [comment]
I think eventually we may need a separate standalone binary for mariadb. I would like to avoid that for as long as possible. If we can tell - based on querying the database - if it is mariadb or mysql, we can determine which template to use.

Even better would be if there is somewhere to determine what the collation is, i.e. capabilities rather than among. 

@peerau do you know how we can accomplish those reliably?

**Comment by peerau** [comment]
`SELECT @@character_set_database, @@collation_database;` seems to work across both mysql and mariadb, i will check version parity now

**Comment by peerau** [comment]
utf8mb4_general_a?_c? might be a sane default?

**Comment by deitch** [comment]
I have an initial cut to query the database and get charset and collation, rather than hard-coding.

I did a quick search, it also appears we set charset in a few other places. 

In view:

```sql
SET @saved_cs_client     = @@character_set_client;
/*!50503 SET character_set_client = utf8mb4 */;
```

In table:

```sql
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!50503 SET character_set_client = utf8mb4 */;
```

Are those correct? Or should those also be taken from a query?

**Comment by deitch** [comment]
Which query? For views, we get them from `SELECT TABLE_NAME,CHARACTER_SET_CLIENT,COLLATION_CONNECTION FROM INFORMATION_SCHEMA.VIEWS`. There is a parallel for tables, is that the right place?

**Comment by deitch** [comment]
I did a similar query, but I am not sure it gives what I expect:

```sql
mysql> SELECT TABLE_NAME,TABLE_COLLATION FROM INFORMATION_SCHEMA.TABLES where table_name = 't1';
+------------+-------------------+
| TABLE_NAME | TABLE_COLLATION   |
+------------+-------------------+
| t1         | latin1_swedish_ci |
+------------+-------------------+
1 row in set (0.00 sec)

mysql> show create table t1;
+-------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Table | Create Table                                                                                                                                                                                                                                                                               |
+-------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| t1    | CREATE TABLE `t1` (
  `id` int(11) DEFAULT NULL,
  `name` varchar(20) DEFAULT NULL,
  `d` date DEFAULT NULL,
  `t` time DEFAULT NULL,
  `dt` datetime DEFAULT NULL,
  `ts` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=latin1 |
+-------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
1 row in set (0.00 sec)
```

On the other hand, if I do a `mysqldump` for that database (just the table part):

```sql
--
-- Table structure for table `t1`
--

DROP TABLE IF EXISTS `t1`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8 */;
CREATE TABLE `t1` (
  `id` int(11) DEFAULT NULL,
  `name` varchar(20) DEFAULT NULL,
  `d` date DEFAULT NULL,
  `t` time DEFAULT NULL,
  `dt` datetime DEFAULT NULL,
  `ts` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=latin1;
/*!40101 SET character_set_client = @saved_cs_client */;

--
-- Dumping data for table `t1`
--

LOCK TABLES `t1` WRITE;
/*!40000 ALTER TABLE `t1` DISABLE KEYS */;
INSERT INTO `t1` VALUES (1,'John','2012-11-01','00:15:00','2012-11-01 00:15:00','2012-11-01 00:15:00'),(2,'Jill','2012-11-02','00:16:00','2012-11-02 00:16:00','2012-11-02 00:16:00'),(3,'Sam','2012-11-03','00:17:00','2012-11-03 00:17:00','2012-11-03 00:17:00'),(4,'Sarah','2012-11-04','00:18:00','2012-11-04 00:18:00','2012-11-04 00:18:00');
/*!40000 ALTER TABLE `t1` ENABLE KEYS */;
UNLOCK TABLES;
```

So we get the CHARSET as part of the `SHOW CREATE TABLE` , which is good. The line just before, though:

```sql
/*!50503 SET character_set_client = utf8mb4 */;
```

Where does it come from?

**Comment by deitch** [comment]
I merged in the fix for this specific issue. But if we can get the remaining `utf*` stuff via queries, by all means. Please help direct.
