### ISSUE TITLE
tgz file not extractable

### ISSUE THREAD

**Issue by topsnet-holgerd** [databacker/mysql-backup#321]
produced several dumps as *.tgz files, none of them can be extracted:

$ tar -xzf db_backup_2024-07-11T23:23:02Z.tgz
tar (child): Cannot connect to db_backup_2024-07-11T23: resolve failed
gzip: stdin: unexpected end of file
tar: Child returned status 128
tar: Error is not recoverable: exiting now

$ gzip -dk db_backup_2024-07-12T08:53:02Z.tgz
$ tar -xvf db_backup_2024-07-12T08:53:02Z.tar
tar: Cannot connect to db_backup_2024-07-12T08: resolve failed

**Comment by deitch** [comment]
Hi @topsnet-holgerd can you share exactly how to reproduce? Or if you have one such file that doesn't have confidential data, upload it here?

**Comment by topsnet-holgerd** [comment]
Sorry, tgz files are not supported:
"We don’t support that file type.
Try again with GIF, JPEG, JPG, MOV, MP4, PNG, SVG, WEBM, CPUPROFILE, CSV, DMP, DOCX, FODG, FODP, FODS, FODT, GZ, JSON, JSONC, LOG, MD, ODF, ODG, ODP, ODS, ODT, PATCH, PDF, PPTX, TGZ, TXT, XLS, XLSX or ZIP."

The Database that should be dumped belongs to Pimcore in a Docker environment.

**Comment by deitch** [comment]
>  I received this message:
"We don’t support that file type.
Try again with GIF, JPEG, JPG, MOV, MP4, PNG, SVG, WEBM, CPUPROFILE, CSV, DMP, DOCX, FODG, FODP, FODS, FODT, GZ, JSON, JSONC, LOG, MD, ODF, ODG, ODP, ODS, ODT, PATCH, PDF, PPTX, TGZ, TXT, XLS, XLSX or ZIP."

From where did you receive that message?

Also, your original error says:

> tar: Cannot connect to db_backup_2024-07-12T08: resolve failed

"Cannot connect" and "resolve failed" implies that it is trying to connect somewhere over the Internet. Can your shell handle all of the characters correctly? Try running tar with verbosity or debug? Did you quote the filename?

**Comment by topsnet-holgerd** [comment]
Allright, I'm sorry. It seemed to be the colons in the name, that prevents tar to extract the file. When replaced by underscores, the file can be extracted. I close this issue.
