### ISSUE TITLE
Cron behaving weirdly?

### ISSUE THREAD

**Issue by maurxce** [databacker/mysql-backup#345]
Hello, I have the following environment variable: `DB_DUMP_CRON=45 23 * * *`.
Now, I expect it to do a daily mysql-dump at 11:45pm, but it seems it’s also doing it at 11pm sharp?
```
# docker compose logs

backup-1  | Starting at Wed Sep 4 18:16:42 UTC 2024
backup-1  | Starting at Wed Sep 4 18:16:46 UTC 2024
backup-1  | ./
backup-1  | ./backup_2024-09-04T23:00:46Z.sql
backup-1  | ./
backup-1  | ./backup_2024-09-04T23:45:48Z.sql
backup-1  | ./
backup-1  | ./backup_2024-09-05T23:00:49Z.sql
backup-1  | ./
backup-1  | ./backup_2024-09-05T23:45:51Z.sql
backup-1  | ./
backup-1  | ./backup_2024-09-06T23:00:53Z.sql
backup-1  | ./
backup-1  | ./backup_2024-09-06T23:45:54Z.sql
```

**Comment by deitch** [comment]
If you are running the older shell-based, don't bother. We aren't fixing anything there at all anymore; switch to the v1.0.0-rc5 or the latest.

If you are running the go based, that _is_ odd. Post some debug logs?

**Comment by maurxce** [comment]
I see, I didn't put a tag for the docker image and ended up using a build from 16 months ago
Let's hope this one works as expected 😄
