### ISSUE TITLE
Support for max_allowed_packet

### ISSUE THREAD

**Issue by wichitalineman** [databacker/mysql-backup#36]
Hello,

We have some tables that have large amounts of data. Our DB is configured like this:

`--max_allowed_packet=268435456"`

When we try to run this image for backups we get the following error:

`mysqldump: Error 2020: Got packet bigger than 'max_allowed_packet' bytes when dumping table`

Would be helpful if we could set max_allowed-packet as ENV.

Thanks

**Comment by deitch** [comment]
That is a good idea. I will try to get around to it, but if you want to put in a Pull Request with a test and implementation, that will get it through faster...

**Comment by deitch** [comment]
I have a generic merge coming in that will handle all vars (including `max_allowed_packets`, but why wouldn't you just set it in the `[mysqldump]` section of your `my.cnf`?
