### ISSUE TITLE
Backup on S3 bucket into specific folder & strange behaviour

### ISSUE THREAD

**Issue by jonathandreyer** [databacker/mysql-backup#363]
Hello everybody,

I did a few tests with an S3 backup (Scaleway), and I wasn't able to backup into a specific folder (e.g. "mysql_backup" folder). My actual deployment is on docker compose. When I choose a mount point (with ``DB_DUMP_TARGET: file:///< FOLDER_NAME >``), it is OK. When I use the root bucket (``DB_DUMP_TARGET: s3://<BUCKET_NAME>``) it is also OK, but not when I choose a folder into the bucket (``DB_DUMP_TARGET: s3://<BUCKET_NAME>/<FOLDER_NAME>``), the program exit correctly but there is not backup into the S3 storage.

I am able to access to the specific S3 folder, for instance, with Cyberduck and the same credentials.

To do my test, I have setup in verbose mode (``-v 2``). The strange point is the output console. In all cases, the program exit correctly, but when I use the S3 storage, the quantity of bytes is 0 (``level=debug msg="completed copying 0 bytes"``).

Is there a bug or somebody has a tip for backuping in a specific S3 folder?

Best regards,

Jonathan Dreyer

**Comment by deitch** [comment]
Hi @jonathandreyer .

I have to say, thanks for the detailed issue. You actually went to the trouble to try different methods to narrow down when it works and when it doesn't.

I assume since you are doing `-v 2` that you are using either the latest commit off of `master` branch, or one of the `v1.0.0-rc*` images.

I want us to get this fixed. Can you post the debug logs here? As always, make sure there is no confidential information. There shouldn't be, as the logging system (in the v1.x+ releases), should log only non-confidential, but it is best not to rely on that and go through it, make sure no logins or credentials slipped in.

Your issue is detailed enough that we should be able to replicate it, but I want to be sure.

**Comment by jonathandreyer** [comment]
Hello @deitch,

My bad, I have forgotten to add the logs, and I had recorded them during my tests. I have also forgotten to mention some other details.
Here are the logs for each of the three scenarios described above. I've also added the docker compose service configuration for each scenario. As you will see, I use the ``-v 2`` to print as much as possible information. In the docker compose configurations, I use the ``databack/mysql-backup:1.0.0-rc5`` image, but I have also tested with the image ``databack/mysql-backup:90912936157673bbf91853e2ef069d47db292dd0``. I have the same behavior with this new image.

**1. Backup into file**

_docker compose :_
```
  mysql-backup:
    image: databack/mysql-backup:1.0.0-rc5
    restart: on-failure
    command: dump --once -v 2
    volumes:
     - ./mysql-backup:/db-backup
    environment:
      ...
      DB_DUMP_TARGET: file:///db-backup
```

_console log :_
```
mysql-backup-1  | time="2024-10-29T22:19:04Z" level=debug msg="starting dump"
mysql-backup-1  | time="2024-10-29T22:19:04Z" level=info msg="beginning dump 2024-10-29T22:19:04Z" run=b6533ac3-3014-483d-88b8-b9f9e252d5ba
mysql-backup-1  | time="2024-10-29T22:19:04Z" level=debug msg="uploading via protocol file from db_backup_2024-10-29T22:19:04Z.tgz" run=b6533ac3-3014-483d-88b8-b
9f9e252d5ba
mysql-backup-1  | time="2024-10-29T22:19:04Z" level=debug msg="completed copying 55933 bytes" run=b6533ac3-3014-483d-88b8-b9f9e252d5ba
mysql-backup-1  | time="2024-10-29T22:19:04Z" level=info msg="Backup complete"
```

**2. Backup into S3 bucket (root directory)**

_docker compose :_
```
  mysql-backup:
    image: databack/mysql-backup:1.0.0-rc5
    restart: on-failure
    command: dump --once -v 2
    environment:
      ...
      DB_DUMP_TARGET: s3://<BUCKET_NAME>
      AWS_ENDPOINT_URL: https://s3.fr-par.scw.cloud
      AWS_ACCESS_KEY_ID: <ACCESS_KEY_ID>
      AWS_SECRET_ACCESS_KEY: <SECRET_ACCESS_KEY>
      AWS_REGION: <REGION>
```

_console log :_
```
mysql-backup-1  | time="2024-10-29T22:25:28Z" level=debug msg="starting dump"
mysql-backup-1  | time="2024-10-29T22:25:28Z" level=info msg="beginning dump 2024-10-29T22:25:28Z" run=49e5c10e-8332-451a-bfaa-3eb36440b96c
mysql-backup-1  | time="2024-10-29T22:25:28Z" level=debug msg="uploading via protocol s3 from db_backup_2024-10-29T22:25:28Z.tgz" run=49e5c10e-8332-451a-bfaa-3eb
36440b96c
mysql-backup-1  | time="2024-10-29T22:25:29Z" level=debug msg="completed copying 0 bytes" run=49e5c10e-8332-451a-bfaa-3eb36440b96c
mysql-backup-1  | time="2024-10-29T22:25:29Z" level=info msg="Backup complete"
```

**3. Backup into S3 bucket (specific folder)**

_docker compose :_
```
  mysql-backup:
    image: databack/mysql-backup:1.0.0-rc5
    restart: on-failure
    command: dump --once -v 2
    environment:
      ...
      DB_DUMP_TARGET: s3://<BUCKET_NAME>/<FOLDER_NAME>
      AWS_ENDPOINT_URL: https://s3.fr-par.scw.cloud
      AWS_ACCESS_KEY_ID: <ACCESS_KEY_ID>
      AWS_SECRET_ACCESS_KEY: <SECRET_ACCESS_KEY>
      AWS_REGION: <REGION>
```

_console log :_
```
mysql-backup-1  | time="2024-10-29T22:45:12Z" level=debug msg="starting dump"
mysql-backup-1  | time="2024-10-29T22:45:12Z" level=info msg="beginning dump 2024-10-29T22:45:12Z" run=d70ce4be-8de8-4c3f-8940-802cec2c6de0
mysql-backup-1  | time="2024-10-29T22:45:12Z" level=debug msg="uploading via protocol s3 from db_backup_2024-10-29T22:45:12Z.tgz" run=d70ce4be-8de8-4c3f-8940-802
cec2c6de0
mysql-backup-1  | time="2024-10-29T22:45:12Z" level=debug msg="completed copying 0 bytes" run=d70ce4be-8de8-4c3f-8940-802cec2c6de0
mysql-backup-1  | time="2024-10-29T22:45:12Z" level=info msg="Backup complete"
```

As a reminder, the scenario 1. and 2. are working well, even if it's strange to have 0 bytes saved for the 2. scenario (whereas the .tar.gz file is 50-60 KB). The scenario 3. doesn't work at all.

Last two points: I didn't test with another S3 storage. I use Scaleway from some backups, and I never have troubles, but we don't know. If necessary, I could try with another S3 platform. Regarding the database dump, it is a MySQL database for [Traccar](https://github.com/traccar/traccar), without many fields, only a few initial values.

Best,

Jonathan Dreyer

**Comment by deitch** [comment]
> PS: I have tested with the latest image (image pushed today), and the behavior is the same. However, the console has a lot considerably more characters

Yeah, there was a bug in how the logging trace levels were passed. That got fixed.

**Comment by deitch** [comment]
> As a reminder, the scenario 1. and 2. are working well, even if it's strange to have 0 bytes saved for the 2. scenario (whereas the .tar.gz file is 50-60 KB). The scenario 3. doesn't work at all.

In your scenario 2, it also says it copied 0 bytes: 
```
mysql-backup-1  | time="2024-10-29T22:25:29Z" level=debug msg="completed copying 0 bytes" run=49e5c10e-8332-451a-bfaa-3eb36440b96c
```

Looks like there might be an issue in the reporting. Can you check directly on your object storage that it did, indeed, copy?

> I didn't test with another S3 storage. I use Scaleway from some backups, and I never have troubles, but we don't know. If necessary, I could try with another S3 platform. 

No, that shouldn't matter in this case. I only would explore that if all other options are exhausted.

> Regarding the database dump, it is a MySQL database for [Traccar](https://github.com/traccar/traccar), without many fields, only a few initial values.

Nah, that doesn't matter. In the end, it is a two-stage process:

1. Dump the database to the file you see referenced in the logs
2. Copy the file to the target

The specific database only matters for the first stage. Once it has a file, the `Push()` doesn't care.

Working on replication. Will update here over the coming days.

**Comment by jonathandreyer** [comment]
> Looks like there might be an issue in the reporting. Can you check directly on your object storage that it did, indeed, copy?

Yes, in this scenario, the object is correctly pushed.

**Comment by jonathandreyer** [comment]
> Yeah, there was a bug in how the logging trace levels were passed. That got fixed.

I see. I wonder if that's a bit much now. In my opinion, it could be interesting to better filtering the console levels between the application code and the dependencies. Now (with ``-v 2``), I have the feeling that the contents of the pushed object are printed in the console.

By putting in verbose, there are also all the messages coming from dependencies (and in this case, there is confidential information reveal).

But now that there's more information in the console, such as the S3 request, the S3 host, .. there is an interesting element. When I run the scenario 3, the PUT request is composed by two ``/``:

**2. Backup into S3 bucket (root directory)**

_console log :_
```
mysql-backup-1  | time="2024-11-01T14:27:45Z" level=debug msg="starting dump"
mysql-backup-1  | time="2024-11-01T14:27:45Z" level=info msg="beginning dump 2024-11-01T14:27:45Z" run=5cbd3eb4-6d78-4868-8f50-19b7ebb2749a
mysql-backup-1  | time="2024-11-01T14:27:45Z" level=debug msg="uploading via protocol s3 from db_backup_2024-11-01T14:27:45Z.tgz to db_backup_2024-11-01T14:27:45Z.tgz" run=5cbd3eb4-6d78-4868-8f50-19b7ebb2749a
mysql-backup-1  | SDK 2024/11/01 14:27:45 DEBUG Request
mysql-backup-1  | PUT /db_backup_2024-11-01T14%3A27%3A45Z.tgz?x-id=PutObject HTTP/1.1
mysql-backup-1  | Host: <BUCKET_NAME>.<ENDPOINT_URI>
mysql-backup-1  | User-Agent: m/E,G aws-sdk-go-v2/1.30.3 os/linux lang/go#1.21.13 md/GOOS#linux md/GOARCH#amd64 api/s3#1.58.2 ft/s3-transfer
mysql-backup-1  | Content-Length: 55978
mysql-backup-1  | Accept-Encoding: identity
mysql-backup-1  | Amz-Sdk-Invocation-Id: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
mysql-backup-1  | Amz-Sdk-Request: attempt=1; max=3
mysql-backup-1  | Authorization: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
mysql-backup-1  | Content-Type: application/octet-stream
mysql-backup-1  | X-Amz-Content-Sha256: UNSIGNED-PAYLOAD
mysql-backup-1  | X-Amz-Date: xxxxxxxxxxxxxxxx
...
..
.
mysql-backup-1  | SDK 2024/11/01 14:27:46 DEBUG Response
mysql-backup-1  | HTTP/2.0 200 OK
mysql-backup-1  | Content-Length: 0
mysql-backup-1  | Date: Fri, 01 Nov 2024 14:27:46 GMT
mysql-backup-1  | Etag: "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
mysql-backup-1  | X-Amz-Id-2: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
mysql-backup-1  | X-Amz-Request-Id: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
mysql-backup-1  | 
mysql-backup-1  | time="2024-11-01T14:27:46Z" level=debug msg="completed copying 0 bytes" run=5cbd3eb4-6d78-4868-8f50-19b7ebb2749a
mysql-backup-1  | time="2024-11-01T14:27:46Z" level=info msg="Backup complete"
```

**3. Backup into S3 bucket (specific folder)**

_console log :_
```
mysql-backup-1  | time="2024-11-01T14:29:18Z" level=debug msg="starting dump"
mysql-backup-1  | time="2024-11-01T14:29:18Z" level=info msg="beginning dump 2024-11-01T14:29:18Z" run=569c3d97-5094-44f3-8737-eaf73c28bffa
mysql-backup-1  | time="2024-11-01T14:29:18Z" level=debug msg="uploading via protocol s3 from db_backup_2024-11-01T14:29:18Z.tgz to db_backup_2024-11-01T14:29:18Z.tgz" run=569c3d97-5094-44f3-8737-eaf73c28bffa
mysql-backup-1  | SDK 2024/11/01 14:29:18 DEBUG Request
mysql-backup-1  | PUT //<SPECIFIC_FOLDER>/db_backup_2024-11-01T14%3A29%3A18Z.tgz?x-id=PutObject HTTP/1.1
mysql-backup-1  | Host: <BUCKET_NAME>.<ENDPOINT_URI>
mysql-backup-1  | User-Agent: m/E,G aws-sdk-go-v2/1.30.3 os/linux lang/go#1.21.13 md/GOOS#linux md/GOARCH#amd64 api/s3#1.58.2 ft/s3-transfer
mysql-backup-1  | Content-Length: 55978
mysql-backup-1  | Accept-Encoding: identity
mysql-backup-1  | Amz-Sdk-Invocation-Id: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
mysql-backup-1  | Amz-Sdk-Request: attempt=1; max=3
mysql-backup-1  | Authorization: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
mysql-backup-1  | Content-Type: application/octet-stream
mysql-backup-1  | X-Amz-Content-Sha256: UNSIGNED-PAYLOAD
mysql-backup-1  | X-Amz-Date: xxxxxxxxxxxxxxxx
...
..
.

mysql-backup-1  | SDK 2024/11/01 14:29:19 DEBUG Response
mysql-backup-1  | HTTP/2.0 200 OK
mysql-backup-1  | Content-Length: 0
mysql-backup-1  | Date: Fri, 01 Nov 2024 14:29:18 GMT
mysql-backup-1  | Etag: "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
mysql-backup-1  | X-Amz-Id-2: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
mysql-backup-1  | X-Amz-Request-Id: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
mysql-backup-1  | 
mysql-backup-1  | time="2024-11-01T14:29:19Z" level=debug msg="completed copying 0 bytes" run=569c3d97-5094-44f3-8737-eaf73c28bffa
mysql-backup-1  | time="2024-11-01T14:29:19Z" level=info msg="Backup complete"
```

**Comment by deitch** [comment]
> I see. I wonder if that's a bit much now. In my opinion, it could be interesting to better filtering the console levels between the application code and the dependencies. Now (with -v 2), I have the feeling that the contents of the pushed object are printed in the console.

`-v=1` is debug, `-v=2` is trace, so it seems appropriate. I wouldn't mind filtering out confidential info, but trace level usually leads to such potential leaking in software.

> composed by two `/`

This one for no folder looks correct:

```
mysql-backup-1  | PUT /db_backup_2024-11-01T14%3A27%3A45Z.tgz?x-id=PutObject HTTP/1.1
mysql-backup-1  | Host: <BUCKET_NAME>.<ENDPOINT_URI>
```

This one for subfolder looks incorrect:

```
mysql-backup-1  | PUT //<SPECIFIC_FOLDER>/db_backup_2024-11-01T14%3A29%3A18Z.tgz?x-id=PutObject HTTP/1.1
mysql-backup-1  | Host: <BUCKET_NAME>.<ENDPOINT_URI>
```

That could be doing it. I have been doing some low-level work with the AWS API (hence, the improved trace-level logging with request/response output, when I discovered it was missing), and I saw that when it is `//` at the beginning, S3 servers tend to be unhappy. Run locally, minio tends to complain and refuse it, but that is service dependent.

Going to work with that locally and see what we get.

Thanks again for the detailed info; it makes it much easier to work with.

**Comment by deitch** [comment]
@jonathandreyer can you try the most recent commit? I made sure the full CI is done before asking. And do it with `-v=2`. It should do the right thing with the path, single `/` at beginning. I cannot confirm that this fixes your issue, but it might, and is the right thing to do anyways.

**Comment by jonathandreyer** [comment]
> @jonathandreyer can you try the most recent commit? I made sure the full CI is done before asking. And do it with `-v=2`. It should do the right thing with the path, single `/` at beginning. I cannot confirm that this fixes your issue, but it might, and is the right thing to do anyways.

Thanks for the fix. Now, the backup file is put in the folder :-) But, the quantity of bytes backup is still ``0 bytes``.

**Comment by deitch** [comment]
Try now.

**Comment by jonathandreyer** [comment]
> Try now.

Thanks for the fix. Now everything works as expected :-) I think we can close this issue.

Best,

Jonathan Dreyer

**Comment by deitch** [comment]
@jonathandreyer can I ask you for a bit of assistance? You wrote that in cases 2 & 3 it works now - which is good - and you are seeing the correct headers when run with `-v 2`. For example fro your above comment:

```yaml
      DB_DUMP_TARGET: s3://<BUCKET_NAME>
      AWS_ENDPOINT_URL: https://s3.fr-par.scw.cloud
      AWS_ACCESS_KEY_ID: <ACCESS_KEY_ID>
      AWS_SECRET_ACCESS_KEY: <SECRET_ACCESS_KEY>
      AWS_REGION: <REGION>
```

which leads to the headers:

```
mysql-backup-1  | PUT /db_backup_2024-11-01T14%3A27%3A45Z.tgz?x-id=PutObject HTTP/1.1
mysql-backup-1  | Host: <BUCKET_NAME>.<ENDPOINT_URI>
```

I have been trying to clean up the handling of endpoints. Yet, when I run the current case against a local S3 server, the bucket does not appear anywhere:

```
$ go run . dump -v 2 --server localhost --port 3306 --target s3://bucket1 --user user --pass userpw --aws-access-key-id xxxx --aws-secret-access-key xxxx  --aws-endpoint-url http://localhost:9000
...
...
PUT /db_backup_2024-11-07T12%3A05%3A54Z.tgz?x-id=PutObject HTTP/1.1
Host: localhost:9000
...
...
```

Note that the `Host` header doesn't have the bucket name, only the endpoint URL. Without the bucket _somewhere_ (`Host` header for virtual-host style, path for path-style), it has no idea what bucket to put it in. Yet yours is working.

Can you confirm that your cases 2 & 3 both show bucket and endpoint in the `Host` header?

**Comment by deitch** [comment]
Ah, ok, never mind. I figured it out. I will be pushing out a new change soon to the main branch. When it is in place, I would appreciate if you can confirm it works correctly before cutting another release.

**Comment by deitch** [comment]
Do you mind looking at the latest `master` and trying it? if it all works correctly, no need for debug logs; if it does not, those two parts of the request - `PUT` and `Host` header - are most interesting.

Thanks

**Comment by jonathandreyer** [comment]
> Do you mind looking at the latest `master` and trying it? if it all works correctly, no need for debug logs; if it does not, those two parts of the request - `PUT` and `Host` header - are most interesting.
> 
> Thanks

I have tested both scenarios (root S3 directory & into a specific S3 directory), and both are working well.

Best,

Jonathan Dreyer
