### ISSUE TITLE
typo ?

### ISSUE THREAD

**Issue by michabbb** [databacker/mysql-backup#379]
https://github.com/databacker/mysql-backup/blob/53080179a922095224b505fa511e41d275454518/examples/docker-compose.yaml#L70

https://github.com/databacker/mysql-backup/blob/53080179a922095224b505fa511e41d275454518/examples/docker-compose.yaml#L52

there is no service test-database here 😏

**Comment by deitch** [comment]
Well oops. 😁 

Thanks for pointing it out; fixing it now.
