### ISSUE TITLE
mysqldump crashes when using the --all-databases flag

### ISSUE THREAD

**Issue by deitch** [databacker/mysql-backup#96]
This appears to be an issue when run with `--all-databases` under alpine:3.9. See https://jira.mariadb.org/browse/MDEV-18782 

Once open, this can be fixed here.

**Comment by CorySanin** [comment]
MariaDB 10.3.15 should have the fix when it gets released (hopefully this week)

**Comment by deitch** [comment]
Yup. Once it is released, need to get it upstreamed into alpine. Will work on it there.
